name: Daily API Scanner & Geolocated Fetch

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [ "main", "test" ]
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'test'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install httpx requests[socks]

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor

      # ================= PROCESS 1: GLOBAL SCANNER =================
      - name: Run Global Scan Script
        run: python scanner.py

      # ================= PROCESS 2: GEOLOCATED SCANNER =================
      # Country: Colombia
      - name: Configure Tor for Colombia (CO)
        run: |
          echo "ExitNodes {co}" | sudo tee /etc/tor/torrc
          echo "StrictNodes 1" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor
          sleep 5
      - name: Run script for Colombia
        run: python proxy.py co

      # Country: Spain
      - name: Configure Tor for Spain (ES)
        run: |
          sudo sed -i '/ExitNodes/d' /etc/tor/torrc
          echo "ExitNodes {es}" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor
          sleep 5
      - name: Run script for Spain
        run: python proxy.py es

      # Country: Canada
      - name: Configure Tor for Canada (CA)
        run: |
          sudo sed -i '/ExitNodes/d' /etc/tor/torrc
          echo "ExitNodes {ca}" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor
          sleep 5
      - name: Run script for Canada
        run: python proxy.py ca

      # Country: United Kingdom
      - name: Configure Tor for United Kingdom (GB)
        run: |
          sudo sed -i '/ExitNodes/d' /etc/tor/torrc
          echo "ExitNodes {gb}" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor
          sleep 5
      - name: Run script for United Kingdom
        run: python proxy.py gb

      # Country: United States
      - name: Run script for USA natively
        run: python proxy.py us

      # ================= COMMIT ALL CHANGES =================
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add lists/list_all.json lists/list_*.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated global and geolocated update: $(date +'%Y-%m-%d %H:%M')" && git push origin test)
