name: Daily API Scanner & Geolocated Fetch

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [ "main", "test" ]
  workflow_dispatch:

jobs:
  run-geolocated-fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country_code: [au, br, ca, co, es, gb, ir, us]
      fail-fast: false 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: 'test'

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run proxy script for ${{ matrix.country_code }}
        run: python scripts/proxy.py ${{ matrix.country_code }}

      # Added a pull rebase loop to handle concurrent pushes smoothly
      - name: Commit country changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add lists/list_${{ matrix.country_code }}.json
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated geolocated update [${{ matrix.country_code }}]"
            
            # Retry loop for push concurrency
            for i in {1..5}; do
              git pull --rebase origin test && git push origin test && break || sleep 5
            done
          else
            echo "No changes detected"
          fi
  
  run-global-scanner:
    needs: run-geolocated-fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: 'test'

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install httpx

      - name: Run Global Scan Script
        run: python scripts/scanner.py

      - name: Commit global changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add lists/list_all.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated global update: $(date +'%Y-%m-%d %H:%M')" && git push origin test)
